### ISSUE TITLE
Can this FrameLayout element be eliminated?

### ISSUE THREAD

**Issue by MPLew-is** [gatech-cs2340-fall2018-group75/nonprofitDonationTrackerApp#15]
https://github.com/gatech-cs2340-fall2018-group75/nonprofitDonationTrackerApp/blob/c7a37e6250c8114e1938665e6d0550bc3dedd5c8/app/src/main/res/layout/activity_results_page_.xml#L2

Lint error attached:
<img width="1402" alt="screen shot 2018-11-08 at 23 43 07 pm" src="https://user-images.githubusercontent.com/11891085/48243783-17eda680-e3b0-11e8-866c-cb8066e5c810.png">

**Comment by MPLew-is** [comment]
It's fine if not, we just have to justify it to the TA (and preferably, add a comment directly in the file).

**Comment by ghost** [comment]
I believe Markian made that layout initially assuming there would be a Fragment, but then made it an activity with a list view. Should be changeable to a LinearLayout or ConstraintLayout to appease the linter @MPLew-is

**Comment by ghost** [comment]
Resolved
